@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "mena",
  "password": "password",
  "email": "teste@test.com",
  "avatarColor": "red",
  "avatarImage": "<add-a-base64-encoded-string>"
}


###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
   "username": "mena",
   "password": "password"
}


###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true
